In [61]:
import numpy as np
import pandas as pd

# STORE

In [62]:
store = pd.read_excel('data/Store_Master.xlsx')

In [63]:
store["isMall"] = 1
store.loc[store["Mall_Name"] == "STANDALONE" ,"isMall"] = 0

In [64]:
store.tail()

Territory Business          Region  Region_Code  Store_Code  \
30  United Arab Emirates      Max  MX - Abu Dhabi          602       60275   
31  United Arab Emirates      Max  MX - Abu Dhabi          602       60301   
32  United Arab Emirates      Max    MX - Sharjah          606       60298   
33  United Arab Emirates      Max  MX - Abu Dhabi          602       60300   
34  United Arab Emirates      Max  MX - Abu Dhabi          602       60299   

                  Store_Name                 Mall_Name Store_Format  \
30        Max Makhani Zakher  Abu Dhabi Co-Op Mall-UAE          NaN   
31    MAX- Abudhabi Al Wahda                  AL Wahda  Mall Stores   
32  MAX - Matejer Al Juraina        Matejer Al Juraina  Mall Stores   
33                   MAX-WTC                       WTC  Mall Stores   
34            MAX-Alain Mall                Alain Mall  Mall Stores   

    Sales_Per_Day Store_Launch_Date Train_Test_Store             Geo_Field  \
30     498.182287        2017-03-20            Train  24.503005, 54.382945   
31   10861.009520        2018-01-30             Test  24.470587, 54.372679   
32    4099.543401        2018-01-07             Test  25.296484, 55.489202   
33    7036.233391        2018-02-01             Test  24.487658, 54.357529   
34    5157.825699        2018-02-01             Test  24.222016, 55.781629   

    Store_Size_Sq_Ft  Customer_Count  Total_Revenue  isMall  
30       2178.431368         13669.0    5271266.780       1  
31      23288.338616             NaN    7472374.550       1  
32       8391.589347             NaN    2820485.860       1  
33       6604.762130             NaN    2701913.622       1  
34       3266.388547             NaN     479677.790       1

In [65]:
# dropping columns which has no distinct values or not useful
store.drop(['Territory', 'Business', 'Store_Name', 'Mall_Name', 'Train_Test_Store','Customer_Count', 'Total_Revenue', 'Geo_Field',\
            'Store_Launch_Date', 'Region' ], inplace=True, axis=1)

In [66]:
store.Store_Format.fillna("Mall Stores", inplace=True)

In [67]:
store.isnull().sum()

Region_Code         0
Store_Code          0
Store_Format        0
Sales_Per_Day       0
Store_Size_Sq_Ft    0
isMall              0
dtype: int64

In [68]:
store.head()

Region_Code  Store_Code        Store_Format  Sales_Per_Day  \
0          602       60077         Mall Stores     544.074849   
1          606       60073         Mall Stores    1251.656549   
2          601       60065         Mall Stores    3319.885702   
3          601       60219  Stand Alone Stores    1211.477261   
4          605       60071         Mall Stores    2221.872874   

   Store_Size_Sq_Ft  isMall  
0       4852.220341       1  
1      13789.949661       1  
2      15609.687991       1  
3       6845.497058       1  
4      12385.047461       0

In [69]:
cols = ['Store_Format']

In [70]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
store[cols] = store[cols].apply(le.fit_transform)

In [71]:
# store.set_index('Store_Code', inplace=True)

In [72]:
from sklearn.preprocessing import MinMaxScaler
minmaxscaler = MinMaxScaler()

In [73]:
store_np = minmaxscaler.fit_transform(store)

/home/vivekviswambharan/anaconda3/envs/3point6/lib/python3.6/site-packages/sklearn/preprocessing/data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [74]:
np.round(store_np,2)

array([[0.2 , 0.1 , 0.  , 0.02, 0.03, 1.  ],
       [1.  , 0.08, 0.  , 0.08, 0.13, 1.  ],
       [0.  , 0.05, 0.  , 0.28, 0.15, 1.  ],
       [0.  , 0.67, 1.  , 0.08, 0.05, 1.  ],
       [0.8 , 0.07, 0.  , 0.18, 0.11, 0.  ],
       [0.6 , 0.04, 0.  , 0.25, 0.03, 0.  ],
       [1.  , 0.09, 0.  , 0.18, 0.08, 0.  ],
       [0.4 , 0.01, 0.  , 0.16, 0.09, 1.  ],
       [0.  , 0.05, 0.  , 0.09, 0.15, 1.  ],
       [0.2 , 0.06, 0.  , 0.13, 0.07, 1.  ],
       [0.  , 0.76, 0.  , 0.  , 0.01, 1.  ],
       [0.  , 0.07, 0.  , 0.28, 0.19, 1.  ],
       [0.  , 0.04, 0.  , 0.04, 0.04, 1.  ],
       [0.8 , 0.08, 0.  , 0.15, 0.02, 1.  ],
       [0.2 , 0.02, 0.  , 0.15, 0.07, 1.  ],
       [1.  , 0.08, 0.  , 0.22, 0.01, 0.  ],
       [0.6 , 0.04, 0.  , 0.15, 0.07, 1.  ],
       [1.  , 0.09, 0.  , 0.18, 1.  , 1.  ],
       [0.2 , 0.06, 0.  , 0.14, 0.05, 1.  ],
       [0.2 , 0.1 , 1.  , 0.08, 0.02, 1.  ],
       [0.  , 0.02, 0.  , 0.16, 0.08, 0.  ],
       [0.  , 0.13, 0.  , 0.21, 0.12, 1.  ],
       [0.

In [75]:
from sklearn.neighbors import NearestNeighbors

In [76]:
nbrs = NearestNeighbors(n_neighbors = 5, algorithm='ball_tree' ).fit(store_np)

In [77]:
distances, indices = nbrs.kneighbors(store_np)

In [78]:
indices

array([[ 0,  9, 18, 14, 29],
       [ 1, 13, 16,  7,  9],
       [ 2, 11, 27, 21, 24],
       [ 3, 19, 10, 25, 23],
       [ 4,  6, 15,  5, 28],
       [ 5,  4, 15,  6, 28],
       [ 6, 15,  4,  5, 28],
       [ 7, 14, 29, 16,  9],
       [ 8, 12, 21,  2, 11],
       [ 9, 18, 14, 29,  0],
       [10, 25, 30, 23, 34],
       [11,  2, 27, 24, 21],
       [12,  8, 21,  0,  9],
       [13, 16,  1,  7, 18],
       [14,  9, 29, 18, 26],
       [15,  6,  4,  5, 28],
       [16,  7, 13, 14,  9],
       [17,  1, 13, 16,  7],
       [18,  9, 14, 29,  0],
       [19,  3,  0, 18,  9],
       [20, 22, 28,  5,  4],
       [21,  2, 11,  8, 27],
       [22, 20, 28,  5,  4],
       [23, 25, 30, 10, 34],
       [24, 27, 11,  2, 21],
       [25, 10, 23, 30, 34],
       [26, 29, 14,  9, 18],
       [27, 11, 24,  2, 21],
       [28, 20, 22,  5,  4],
       [29, 14,  9, 18, 26],
       [30, 25, 23, 10, 34],
       [31, 33, 34, 23, 25],
       [32, 34, 33, 30, 23],
       [33, 34, 31, 30, 23],
       [34, 33

In [79]:
distances

array([[0.        , 0.12458218, 0.12681712, 0.16156148, 0.19380059],
       [0.        , 0.23645666, 0.41162293, 0.61034096, 0.80347542],
       [0.        , 0.04242895, 0.09222977, 0.11653979, 0.13886118],
       [0.        , 0.59989843, 1.00815742, 1.00870476, 1.02693782],
       [0.        , 0.20305009, 0.22645446, 0.23051878, 0.61465417],
       [0.        , 0.23051878, 0.40373674, 0.41171718, 0.43321818],
       [0.        , 0.07571626, 0.20305009, 0.41171718, 0.81563108],
       [0.        , 0.20098172, 0.20178388, 0.20457381, 0.20883178],
       [0.        , 0.12188325, 0.14413713, 0.18959861, 0.19426764],
       [0.        , 0.02557186, 0.04428661, 0.07690441, 0.12458218],
       [0.        , 0.07743276, 0.24285879, 0.26085229, 0.55049323],
       [0.        , 0.04242895, 0.0700843 , 0.11833397, 0.11959573],
       [0.        , 0.12188325, 0.20926681, 0.21039153, 0.22191534],
       [0.        , 0.20726868, 0.23645666, 0.41101727, 0.60095347],
       [0.        , 0.04428661, 0.

In [80]:
#        [31, 33, 34, 24, 27],
#        [32,  1, 13, 16,  7],
#        [33, 34, 24, 26, 31],
#        [34, 33, 26,  2, 24]
        
store.head()

Region_Code  Store_Code  Store_Format  Sales_Per_Day  Store_Size_Sq_Ft  \
0          602       60077             0     544.074849       4852.220341   
1          606       60073             0    1251.656549      13789.949661   
2          601       60065             0    3319.885702      15609.687991   
3          601       60219             1    1211.477261       6845.497058   
4          605       60071             0    2221.872874      12385.047461   

   isMall  
0       1  
1       1  
2       1  
3       1  
4       0

In [95]:
store.ix[27,:]['Store_Code']

/home/vivekviswambharan/anaconda3/envs/3point6/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


60061.0

In [ ]:
# 60299 - > 60057,  60065, 60068
# 60300 ->  60057, 60068
# 60298 -> 60073, 60072, 60064, 60055
# 60301 ->60068, 60061